# Generated by Django 5.0.4 on 2024-04-19 11:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opinia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocena', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('tresc', models.CharField(max_length=100)),
                ('data', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Opinie',
            },
        ),
        migrations.CreateModel(
            name='Podroz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Podróże',
            },
        ),
        migrations.CreateModel(
            name='SrodekTransportu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('droga_przewozu', models.TextField(choices=[('Ld', 'Lądowa'), ('Mr', 'Morska'), ('Pw', 'Powietrzna')])),
            ],
            options={
                'verbose_name_plural': 'Środki Transportu',
            },
        ),
        migrations.CreateModel(
            name='Bilet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(default='nieopłacony')),
                ('podroz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.podroz')),
            ],
            options={
                'verbose_name_plural': 'Bilety',
            },
        ),
        migrations.AddField(
            model_name='podroz',
            name='srodek_transportu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.srodektransportu'),
        ),
    ]
