# Generated by Django 5.0.4 on 2024-04-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='podroz',
            name='do',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='podroz',
            name='z',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='srodektransportu',
            name='nazwa',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='srodektransportu',
            name='przewoznik',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='srodektransportu',
            name='typ',
            field=models.TextField(default=''),
        ),
    ]
