# Generated by Django 5.0.4 on 2024-04-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_podroz_do_podroz_z_srodektransportu_nazwa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilet',
            name='status',
            field=models.CharField(default='nieopłacony', max_length=100),
        ),
        migrations.AlterField(
            model_name='podroz',
            name='do',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='podroz',
            name='z',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='srodektransportu',
            name='nazwa',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='srodektransportu',
            name='przewoznik',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='srodektransportu',
            name='typ',
            field=models.CharField(max_length=100),
        ),
    ]
