# Generated by Django 5.0.4 on 2024-04-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_bilet_status_alter_podroz_do_alter_podroz_z_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilet',
            name='status',
            field=models.BooleanField(default=0),
        ),
    ]
