# Generated by Django 5.0.4 on 2024-04-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_bilet_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bilet',
            name='godzina_do',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bilet',
            name='godzina_z',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
