# Generated by Django 5.0.4 on 2024-04-22 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_bilet_dodatkowe_oplaty_bilet_nr_siedzenia'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Podroz',
            new_name='Kierunek',
        ),
        migrations.AlterModelOptions(
            name='kierunek',
            options={'verbose_name_plural': 'Kierunki'},
        ),
        migrations.RenameField(
            model_name='bilet',
            old_name='podroz',
            new_name='kierunek',
        ),
    ]
